// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"400","screenHeight":"500","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"TitleNewGameOnly","status":true,"description":"ニューゲームオンリープラグイン","parameters":{"startString":" ","font":"","fileExistAction":"0","soundEffect":"","adjustY":"0"}},
{"name":"Oggy_CustomLoading","status":true,"description":"v1.00 This plugin customizes a loading ui","parameters":{}},
{"name":"PictureCallCommon","status":true,"description":"ピクチャのボタン化プラグイン","parameters":{"透明色を考慮":"true","ピクチャ番号の変数番号":"0","ポインタX座標の変数番号":"0","ポインタY座標の変数番号":"0","タッチ操作抑制":"false","戦闘中常にコモン実行":"false","無効スイッチ":"0"}},
{"name":"PictureDrag","status":true,"description":"ピクチャのドラッグ移動プラグイン","parameters":{}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"OnlineAvatars","status":true,"description":"Firebaseを使ってプレイヤーをオンライン同期します。","parameters":{"apiKey":"AIzaSyA9y_1vVUh_yOu-gmbqpbYGx6_tvHUyAsA","authDomain":"chatsystem-56aef.firebaseapp.com","databaseURL":"https://chatsystem-56aef.firebaseio.com","avatarEvent":"0","syncSwitchStart":"0","syncSwitchEnd":"0","syncVariableStart":"21","syncVariableEnd":"80"}},
{"name":"111_InputForm","status":true,"description":"フォーム作って文字入力（修正版）","parameters":{}},
{"name":"ServerTime","status":true,"description":"サーバータイムを取得します。","parameters":{}},
{"name":"Torigoya_SaveCommand2","status":true,"description":"プラグインコマンドからセーブを実行できるようにします。","parameters":{}}
];
